### ISSUE TITLE
Herokuについて調べる

### ISSUE THREAD

**Issue by haruguchi-yuma** [haruguchi-yuma/reread#36]
- [x] Herokuとは何なのか
- [x] Herokuにできることを確認する
- [x] 実際にHerokuを使って簡単なアプリを作ってみる

**Comment by haruguchi-yuma** [comment]
## Herokuとは
PaaSの一つで、開発したWEBアプリケーションを簡単に全世界に公開でき、本格的にサービスの保守運用が可能なホスティングサービス。

## ホスティングサービス
じゃあ、ホスティングサービスとはなんだという話。

ホスティングサービスとは、サーバの貸し出しサービスで自社でサーバを購入しなくてもいいのが利点。

ホスティングサービスには次のようなものがある。
- SaaS(Software as a Service)
- PaaS(Platform as a Service)
- IaaS(infrastructure as a Service)

### SaaS
ソフトウェアをインターネットを通じて提供するサービス。
Googleのアプリ全般（Google MapsとかGmailとか。)
ScrapboxとかEvernoteとかのその類。

データをクラウド上に置いておくのでオンラインで編集などが可能。インターネットに繋がってないと利用できない。

### Paas
アプリケーション開発者向けのサービスで、アプリケーションのプログラムに関するプラットフォームをインターネットで提供する。アプリケーションの作成、環境設定の手間を削減できる。

AWS,Microsoft Azure , Herokuなど。

開発環境を提供してくれるものと思っておけばいいのかも。

### IaaS
これはプラットフォームから自分で色々構築していくタイプ。

Google Compute Engine, EC2など。

インフラの知識が必要。

**Comment by dowdiness** [comment]
選択肢を増やすことで迷わせるかもしれませんが、最近出てきたrenderというサービスが結構使いやすくてオススメですよ。
https://render.com/render-vs-heroku-comparison

**Comment by haruguchi-yuma** [comment]
適当なアプリをHerokuでデプロイできた
https://sample-heroku-app-with-shrine.herokuapp.com/photos

参考：
https://qiita.com/kazukimatsumoto/items/a0daa7281a3948701c39
失敗した時の参考
https://qiita.com/m6mmsf/items/fb8a8672df98bdb59c9c

**Comment by haruguchi-yuma** [comment]
@dowdiness 
ありがとうございます。render初めて聞きました。調べてみますね！

**Comment by haruguchi-yuma** [comment]
上記タスクを満たしたためcloseする。

**Comment by haruguchi-yuma** [comment]
feature/loading-notifications-with-placeholder
