### ISSUE TITLE
DB設計

### ISSUE THREAD

**Issue by haruguchi-yuma** [haruguchi-yuma/reread#4]

**Comment by haruguchi-yuma** [comment]
## 初版
![image](https://user-images.githubusercontent.com/57053236/148170912-4e98dc4e-5ca1-48cd-ac43-2c9edc286050.png)


- Usersテーブル
    - OmniAuthでのGithub認証のため`provider``uid`を持たせている
    - `image_url`はGitHubのアイコンを表示させるため

- Photosテーブル
    - gem`shrine`は`<カラム_data>`という属性にする必要があるため`image_data`とした
    - noteは画像に紐づける簡単な任意入力のメモであるが、必要かどうかは実装して決めたいと思う。

- ReadHistoriesテーブル
    - googleカレンダーに再読日を設定するが、アプリ本体にもデータとして持たせて履歴一覧などがみられると良いと考えられるため作ったテーブル。本当に必要かどうか実装して検討したい。

**Comment by komagata** [comment]
確認しました、OKですー🙆‍♂️

（migrationの仕組みで必要になった時に追加できるので、今必要ないものは作らず、必要になったときに追加するといいと思います〜）

**Comment by haruguchi-yuma** [comment]
レビューありがとうございます。
最初は必要最低限で実装して必要になった時点で追加していきます！
