### ISSUE TITLE
URL設計

### ISSUE THREAD

**Issue by haruguchi-yuma** [haruguchi-yuma/reread#5]

**Comment by haruguchi-yuma** [comment]
|Method| Path| Description |
| --- | --- | --- |
| GET | / | トップページ、アプリの詳細 |
| GET | /auth/:provider/callback | ログイン/ユーザの作成処理を実行 |
| DELETE | /logout | ログアウトを実行 |

[WIP]

**Comment by komagata** [comment]
絶対ではないですが、`/retirements/new`の退会は一つだと思うので単数系の方がいいかな〜と思いました。

**Comment by haruguchi-yuma** [comment]
確かに退会は単数ですね。変更しました！

**Comment by komagata** [comment]
確認しました、OKですー🙆‍♂️
